-- MySQL Script generated by MySQL Workbench
-- Tue 02 May 2017 02:58:28 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema photoslider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema photoslider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photoslider` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `photoslider` ;

-- -----------------------------------------------------
-- Table `photoslider`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoslider`.`theme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `on` TINYINT(1) NOT NULL,
  `showFirst` boolean NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoslider`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoslider`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `filePath` VARCHAR(150) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoslider`.`soundeffect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoslider`.`soundeffect` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Soundeffect_Media1_idx` (`id` ASC),
  CONSTRAINT `fk_Soundeffect_Media1`
    FOREIGN KEY (`id`)
    REFERENCES `photoslider`.`media` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoslider`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoslider`.`photo` (
  `id` INT NOT NULL,
  `Soundeffect_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Photo_Media1_idx` (`id` ASC),
  INDEX `fk_Photo_Soundeffect1_idx` (`Soundeffect_id` ASC),
  CONSTRAINT `fk_Photo_Media1`
    FOREIGN KEY (`id`)
    REFERENCES `photoslider`.`media` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Photo_Soundeffect1`
    FOREIGN KEY (`Soundeffect_id`)
    REFERENCES `photoslider`.`soundeffect` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoslider`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoslider`.`song` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Song_Media1_idx` (`id` ASC),
  CONSTRAINT `fk_Song_Media1`
    FOREIGN KEY (`id`)
    REFERENCES `photoslider`.`media` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoslider`.`theme_has_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoslider`.`theme_has_media` (
  `theme_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  PRIMARY KEY (`theme_id`, `media_id`),
  INDEX `fk_Theme_has_Media_Media1_idx` (`media_id` ASC),
  INDEX `fk_Theme_has_Media_Theme1_idx` (`theme_id` ASC),
  CONSTRAINT `fk_Theme_has_Media_Theme1`
    FOREIGN KEY (`theme_id`)
    REFERENCES `photoslider`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Theme_has_Media_Media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `photoslider`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

GRANT ALL PRIVILEGES ON photoslider.* TO 'PAD'@'%' IDENTIFIED BY 'fissafissaheey123';
